#test autoencoder on larger_dataset_k533_input128_1000epoch
#[0]128data_k533_input128
#[1]1024data_k533_input128
#[2]4096data_k533_input128


EXP_NAME : "128data_k533_input128" #EXP_NAME used to distinguish each run
OUT: "autoencoder_out" #path to output directory
SYSTEM:
  DEVICE: cuda
  GPU_IDS: 0
  NUM_GPUS: 1
  NUM_CPUS: 2
MODEL:
  INPUT_SIZE: [ 128, 128,128 ]
  ARCHITECTURE: autoencoder
  # BLOCK_TYPE can be 'single' 'double' 'residual' or empty(will use one conv each layer)
  BLOCK_TYPE:  
  FILTERS: [32,64,96]
  kernel_size: [5,3,3]
  IN_PLANES: 1
  OUT_PLANES: 1 
  PAD_MODE: 'reflect'
  ACT_MODE: 'elu'
  NORM_MODE: 'none'
  UPSAMPLE_INTERP: False #whether use linear_interpolation to upsample 
  contrastive_mode: False
LOSS:
  #####for reconstruntion loss
  name: l1 
  #####for contrastive loss, not used yet
  n_views: 2
  temperature: 0.07
TRAINER:
  name: 'trainer' #Trainer to choose
  save_every: 50 #save frequency
  epoch: 1000
  fp16: False 
SOLVER:
  LR_SCHEDULER_NAME: "cosine"
  NAME: "adam"
  LR_START: 5e-4
  LR_END: 1e-6
  WEIGHT_DECAY: 0.0
  LR_WARMUP: 10
DATASET:
  e5: False 
  name: 'visor_dataset'
  batch_per_gpu: 16
  num_workers: 0
  shuffle: True
  ######for fixed dataset######
  raw_img_path: "/home/confetti/mnt/data/processed/t1779/t1779.ims" 
  label_path: "/home/confetti/mnt/data/processed/t1779/r32_ims_downsample_561_register/registered_atlas.tiff"
  data_path_dir: "/home/confetti/mnt/data/processed/t1779/128roi_skip_gapped"
  valid_data_path_dir: "/home/confetti/mnt/data/processed/t1779/recon_test"

  #not used here
  mask_path_dir: "/home/confetti/mnt/data/processed/t1779/choosen_choosen_mask"
  e5_raw_img_path: "/share/data/VISoR_Reconstruction/SIAT_SIAT/BiGuoqiang/Mouse_Brain/20210131_ZSS_USTC_THY1-YFP_1779_1/Reconstruction_1.0/z00000_c1.ims" 
  e5_raw_mask_path: "/share/home/shiqiz/data/t1779/r32_ims_downsample_561_register/registered_atlas.tiff"
  e5_data_path_dir: "/share/home/shiqiz/data/t1779/128roi_skip_gapped"
  e5_valid_data_path_dir: "/share/home/shiqiz/data/t1779/recon_test"
  e5_mask_path_dir: "/share/home/shiqiz/data/t1779/choosen_choosen_mask" 

  ######for random generated dataset, not used here ######
  amount: 1000   #total amount of training data , only valid for radom_generated dataset
  level: 0
  channel: 2
  voxel_size: 1 #(um)
  min_valid_texture_length:  48 #(um)
  zoom_factor: 25
  input_size: [128,128,128]

   # preprocess_mode: 'tensor' "norm" . "clip_norm"
  # if use norm or clip, remeber to synchronize with valid and test dataset
  preprocess_mode: 'tensor'
  preprocess_instance : False
  # clip will be used in clip, norm and color-brightness adjustment
  clip_low : 96
  clip_high : 4000
  #augmentation transform_type : rotation_color_blur:
  transform_type : [False,False,False]
  # transform_type : [True,True,True]
  return_mask: False 
  label_in_name: True
  random: False 



