
EXP_NAME : "test3contrastive_unet_sgdata" #EXP_NAME used to distinguish each run
OUT: "out" #path to output directory
SYSTEM:
  e5: True #control dataset_path to use on cluster or local
  DEVICE: cuda
  GPU_IDS: 0
  NUM_GPUS: 1
  NUM_CPUS: 2
MODEL:
  INPUT_SIZE: [ 32, 32, 32 ]
  ARCHITECTURE: autoencoder
  # BLOCK_TYPE can be 'single' 'double' 'residual' or empty(will use one conv each layer)
  BLOCK_TYPE:  
  FILTERS: [16,32,64]
  IN_PLANES: 1
  OUT_PLANES: 64 
  PAD_MODE: 'reflect'
  ACT_MODE: 'elu'
  NORM_MODE: 'gn'
  UPSAMPLE_INTERP: False #whether use linear_interpolation to upsample 
  contrastive_mode: True
LOSS:
  #####for reconstruntion loss
  name: contrastive_loss 
  #####for contrastive loss, not used yet
  n_views: 2
  temperature: 0.07
TRAINER:
  name: 'contrastive_trainer' #Trainer to choose
  save_every: 50 #save frequency
  epoch: 3000
  fp16: False 
SOLVER:
  LR_SCHEDULER_NAME: "cosine"
  NAME: "adam"
  LR_START: 5e-4
  LR_END: 1e-6
  WEIGHT_DECAY: 0.0
  LR_WARMUP: 10
DATASET:
  name:  random_visor
  batch_per_gpu: 1
  num_workers: 0
  shuffle: True
  ######for fixed dataset######
  data_path_dir: "/home/confetti/mnt/data/processed/t1779/128roi_skip_gapped"
  e5_data_path_dir: "/share/home/shiqiz/data/t1779/128roi_skip_gapped"
  valid_data_path_dir: "/home/confetti/mnt/data/processed/t1779/skip_gapped_test"
  e5_valid_data_path_dir: "/share/home/shiqiz/data/t1779/skip_gapped_test"
  ######for random generated dataset, not used here ######
  amount: 1000   #total amount of training data , only valid for radom_generated dataset
  raw_img_path: "/home/confetti/data/mousebrainatlas/T11.ims.h5" 
  label_path: "/home/confetti/data/mousebrainatlas/new_t11/registered_atlas.tiff"
  # raw_img_path: "/home/confetti/mnt/data/processed/t1779/t1779.ims" 
  # label_path: "/home/confetti/mnt/data/processed/t1779/r32_ims_downsample_561_register/registered_atlas.tiff"
  # raw_img_path: "/share/data/VISoR_Reconstruction/SIAT_SIAT/BiGuoqiang/Mouse_Brain/20210131_ZSS_USTC_THY1-YFP_1779_1/Reconstruction_1.0/z00000_c1.ims" 
  # label_path: "/share/home/shiqiz/data/t1779/r32_ims_downsample_561_register/registered_atlas.tiff"
  level: 0
  channel: 2
  voxel_size: 1 #(um)
  min_valid_texture_length:  48 #(um)
  zoom_factor: 25
  input_size: [32,32,32]
  IS_ISOTROPIC: True 
PREPROCESS:
  # only when NORM is True, NORM_MODE will func
  NORM: False 
  NORM_MODE: "min_max"
  # used to clip the data
  # for 100roi dataset, 96 is the global_min value, 2672 is the 99 percentile global_high value, to exclude some extra high value in data
  clip_low : 96 
  clip_high : 2672


